# Generated by Django 3.2.16 on 2023-02-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
    ]
